language: node_js
node_js: 
  - 13

services:
  - docker

install:
  - echo "nothing need to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t simple-node-travis .
  - docker tag simple-node-travis jeskii/simple-node-travis:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jeskii/simple-node-travis
